Users settings
VinetiInternship2021/final-project-GG pull request #13
Opened 2021-05-11 13:25 UTC by ArtyomKosakyan

Added settings functionality for Admin,Passenger,Driver. They can change his phone_number, name and etc.
Added "active" and "verified" indicators for Driver.

2021-05-13 16:28 UTC, iwazowsky approved these changes
MIght need some refactoring to keep code DRY, but overall it's fine

2021-05-14 06:54 UTC, vnersisyan-vineti requested changes
minor comments

2021-05-14 06:54 UTC, vnersisyan-vineti commented on src/components/Admin/ClientFieldPassenger.js
> +    id, phoneNumber, firstName, lastName,
destruct in props please

2021-05-14 06:54 UTC, vnersisyan-vineti commented on src/components/Admin/ClientList.js
> +      {userId
userId && ()

2021-05-14 06:54 UTC, vnersisyan-vineti commented on src/components/Buttons.js
>              className={className}
className can be not required props, and has default value `''`, in that case you can remove ternary operator

2021-05-14 06:54 UTC, vnersisyan-vineti commented on src/components/Client/Taxi.js
> +  const { userId } = appState;
destruct in props

2021-05-14 06:54 UTC, vnersisyan-vineti commented on src/components/Driver/DriverPage.js
> +        {showConfirm
showConfirm && ()

2021-05-14 06:54 UTC, vnersisyan-vineti commented on src/components/Driver/DriverPage.js
> +      {userId
userId && ()

2021-05-14 06:54 UTC, vnersisyan-vineti commented on src/components/Driver/DriverProfile.js
> +      {userId
userId && ()

2021-05-14 06:54 UTC, vnersisyan-vineti commented on src/components/Driver/DriverSettings.js
> +      {userId
userId && ()

2021-05-14 06:54 UTC, vnersisyan-vineti commented on src/components/Driver/DriverProfile.js
>      userId: match.params.id,
destruct in props

2021-05-14 06:54 UTC, vnersisyan-vineti commented on src/components/Driver/DriverSettings.js
> +  const userId = match.params.id;
destruct in props

2021-05-14 06:54 UTC, vnersisyan-vineti commented on src/components/RegistrationForm.js
>  };
put empty line

2021-05-14 06:54 UTC, vnersisyan-vineti commented on src/utils/ProfileSettingsFields.js
> +  ));
empty line here

2021-05-14 06:57 UTC, ArtyomKosakyan commented on src/components/Client/Taxi.js
> +  const { userId } = appState;
I used appState too

2021-05-14 07:35 UTC, vnersisyan-vineti approved these changes
Awesome

2021-05-14 07:36 UTC, merged