added verification feature
VinetiInternship2021/final-project-GG pull request #22
Opened 2021-05-19 04:23 UTC by Aram-Abovyan

2021-05-19 06:28 UTC, vnersisyan-vineti requested changes
Minor comments, please address

2021-05-19 06:28 UTC, vnersisyan-vineti commented on GG_clone_backend/db/seeds.rb
> +#                  password_digest: SuperUser.digest('Admin1234'))
same comment as in previous PR, if not used remove comment part

2021-05-19 06:28 UTC, vnersisyan-vineti commented on src/components/Admin/ClientFieldDriver.js
>    let verified = 'bg-danger';
rename verified variable name to `verifiedClassName`
`const verifiedClassName = isVerifiedByAdmin ? 'bg-success' : 'bg-danger';
`const activeClassName = isActive && isVerifiedByAdmin ? 'bg-success' : 'bg-danger';

2021-05-19 06:28 UTC, vnersisyan-vineti commented on src/components/Admin/verification/UnverifiedDriverList.js
> +          setUnverifiedDrivers(unverifiedDrivers.filter((driver) => driver.id !== id));
separate new drivers to variable, then pass it to `setUnverifiedDrivers`

2021-05-19 06:28 UTC, vnersisyan-vineti commented on src/components/Admin/verification/UnverifiedDriverList.js
> +      .then((res) => {
`({ data })` - do destruction in argument section

2021-05-19 06:28 UTC, vnersisyan-vineti commented on src/components/Admin/verification/validateDriver.js
> +  return Object.fromEntries(Object.entries(driver).map((item) => [camlecase(item[0]), item[1]]));
`.map((item) => [camlecase(item[0]), item[1]]));` to not have array indexes here, destruct in map params section, `.map([name1, name2])`, and also name those variables with field names

2021-05-23 16:11 UTC, iwazowsky commented on GG_clone_backend/db/seeds.rb
> -Passenger.create({ first_name: 'Hakob', last_name: 'Arshakyan', phone_number: '+37444556699',
This manual seeds are required for testing, please keep them

2021-05-24 16:00 UTC, ArtyomKosakyan commented on GG_clone_backend/app/controllers/api/v1/unverified_drivers_controller.rb
> +class Api::V1::UnverifiedDriversController < ApplicationController
On my opinion we can write this functionality in drivers_controller for example, but we don't have time, dont change

2021-05-24 16:02 UTC, ArtyomKosakyan commented on src/components/Admin/ClientField.js
> +/* eslint-disable */
Why Eslint disable ?

2021-05-24 16:03 UTC, ArtyomKosakyan commented on src/components/Admin/ClientFieldDriver.js
> +/* eslint-disable */
Why disabled?

2021-05-25 10:21 UTC, ArtyomKosakyan approved these changes

2021-05-25 13:26 UTC, vnersisyan-vineti approved these changes
Approve

2021-05-25 14:49 UTC, merged